part of 'chat_page.dart';

extension _ChatPagePersistenceExt on _ChatPageState {
  /// Saves the currently enabled tool names to the active conversation.
  /// This ensures per-conversation tool preferences persist across sessions.
  void _saveEnabledToolsToConversation() {
    final convId = ref.read(activeConversationIdProvider);
    if (convId == null) return;
    final enabledTools = ref.read(enabledToolNamesProvider);
    final convs = ref.read(conversationsProvider);
    final conv = convs.where((c) => c.id == convId).firstOrNull;
    if (conv == null) return;
    // 从未配置过偏好的对话：运行时集与当前自动启用基线一致（用户没有
    // 手动偏离过）时不写入——保持"未配置"状态，MCP 总开关重新开启后
    // 下次解析会自动重新启用 MCP 工具；用户手动开关过（集合偏离基线，
    // 含全部关闭）才冻结为显式偏好。否则第一次发送就会把"当时可选择"
    // 的集合永久固化，被总开关隐藏过的 MCP 工具再也不会回来。
    if (!conv.hasExplicitEnabledMcpTools &&
        setEquals(
          enabledTools,
          _adapter.getAllToolDefinitions().map((t) => t.name).toSet(),
        )) {
      return;
    }
    // Only persist if the set actually changed to avoid unnecessary writes
    if (conv.enabledMcpToolNames.length != enabledTools.length ||
        !conv.enabledMcpToolNames.containsAll(enabledTools)) {
      // We need to update the conversation's enabledMcpToolNames.
      // Since Conversation is mutable, we update it in-place and let
      // the existing _persist mechanism handle the save.
      // Access the notifier to trigger persistence.
      ref.read(conversationsProvider.notifier).updateEnabledTools(
            convId,
            enabledTools,
          );
    }
  }

  Future<void> _saveMessages({String? capturedConvId}) async {
    final historySnapshot = List<ChatMessage>.from(_history);
    try {
      final convId = capturedConvId ?? ref.read(activeConversationIdProvider);
      if (convId == null) return;
      await ref.read(conversationsProvider.notifier).updateMessages(convId, [
        ...historySnapshot,
      ]);
    } catch (e, s) {
      // Fallback: save directly to SharedPreferences if the notifier is
      // unavailable (e.g. during background streaming after page disposal).
      debugPrint('_saveMessages via notifier failed: $e\n$s');
      await AppLogService.error('ChatPage', '通过 notifier 保存消息失败, 尝试直接写入', e, s);
      try {
        final prefs = await SharedPreferences.getInstance();
        final convId = capturedConvId ?? ref.read(activeConversationIdProvider);
        if (convId == null) return;

        // Tier A: read existing, modify the target conversation, write back.
        // We round-trip the other conversations through Conversation.fromMap →
        // toMap so that any pre-existing unsanitized base64 in their
        // rawRequest/rawResponse is stripped (this prevents the
        // SharedPreferences file from being re-bloated by unsanitized data
        // from older app versions or from a previous failed save).
        try {
          final allJson = prefs.getString('conversations');
          if (allJson != null && allJson.isNotEmpty) {
            final decoded = jsonDecode(allJson);
            if (decoded is List) {
              final list = <Map<String, dynamic>>[];
              for (final item in decoded) {
                if (item is Map) {
                  try {
                    // Round-trip through fromMap/toMap to strip any
                    // unsanitized large base64 in rawRequest/rawResponse.
                    final conv =
                        Conversation.fromMap(Map<String, dynamic>.from(item));
                    list.add(conv.toMap());
                  } catch (_) {
                    // If we can't round-trip this conversation, drop it.
                    // The new conversation will be added below.
                    debugPrint(
                        '_saveMessages Tier A: dropping unparseable conversation');
                  }
                }
              }
              // Find or insert the target conversation
              final existingIdx = list.indexWhere((c) => c['id'] == convId);
              final targetMap = <String, dynamic>{
                'id': convId,
                'title': '',
                'createdAt': DateTime.now().toIso8601String(),
                'updatedAt': DateTime.now().toIso8601String(),
                'messages': historySnapshot.map((m) => m.toMap()).toList(),
                'isPinned': false,
                'sortOrder': 0,
                'draftText': '',
              };
              if (existingIdx >= 0) {
                final existing = list[existingIdx];
                // 完整保留现有条目的全部字段（含上下文管理状态
                // contextSummary / compactionTailStartId、usage 计量
                // lastInputTokens / lastOutputTokens / totalCost、
                // titleAutoGenerated / lastUsedModelName、assistantId、
                // 工具偏好等），再覆盖新消息列表与时间戳。逐个字段
                // 保留会漏掉新增字段（压缩/计量状态会被清零）。
                targetMap
                  ..addAll(Map<String, dynamic>.from(existing))
                  ..['id'] = convId
                  ..['updatedAt'] = DateTime.now().toIso8601String()
                  ..['messages'] =
                      historySnapshot.map((m) => m.toMap()).toList();
                list[existingIdx] = targetMap;
              } else {
                list.insert(0, targetMap);
              }
              final json = jsonEncode(list);
              await prefs.setString('conversations', json);
              await AppLogService.warning(
                  'ChatPage', '通过直接写入 SharedPreferences 成功保存消息 (Tier A)');
              return;
            }
          }
        } catch (eA, sA) {
          debugPrint('_saveMessages Tier A failed: $eA\n$sA');
          await AppLogService.error(
              'ChatPage', '保存消息失败 (Tier A: 修改现有对话)', eA, sA);
        }

        // Tier B: existing data is missing or corrupt — overwrite with just
        // this conversation. The user's history is preserved because the
        // backup keys (conversations.corrupt.*) created by _load still
        // contain the undecodable data for manual recovery.
        try {
          final convMap = <String, dynamic>{
            'id': convId,
            'title': '',
            'createdAt': DateTime.now().toIso8601String(),
            'updatedAt': DateTime.now().toIso8601String(),
            'messages': historySnapshot.map((m) => m.toMap()).toList(),
            'isPinned': false,
            'sortOrder': 0,
            'draftText': '',
          };
          final json = jsonEncode([convMap]);
          await prefs.setString('conversations', json);
          await AppLogService.error(
              'ChatPage', '通过直接写入 SharedPreferences 成功保存消息 (Tier B - 仅当前对话)');
        } catch (eB, sB) {
          debugPrint('_saveMessages Tier B failed: $eB\n$sB');
          await AppLogService.error(
              'ChatPage', '保存消息失败 (Tier B: 全新写入)', eB, sB);
        }
      } catch (eOuter, sOuter) {
        debugPrint('_saveMessages outer fallback failed: $eOuter\n$sOuter');
        await AppLogService.error('ChatPage', '保存消息失败 (外层兜底)', eOuter, sOuter);
      }
    }
  }

  Future<void> _onMessageSend(String text, List<Attachment> attachments) async {
    // Guard: only block sending if THIS conversation is streaming,
    // not if another conversation happens to be streaming elsewhere.
    String? convId = ref.read(activeConversationIdProvider);
    if (convId != null &&
        ref.read(streamingConversationsProvider).contains(convId)) {
      return;
    }
    // Synchronous guard: prevent double-send from rapid Enter / button taps
    // during the async gap between the guard above and the synchronous
    // _streams insertion inside manager.startStreaming.
    if (convId != null && _pendingSendConvIds.contains(convId)) return;
    try {
      await AppLogService.info(
          'ChatPage',
          '发送消息, convId=$convId, text长度=${text.length}, '
              'attachments=${attachments.length}');
      if (convId == null) {
        await AppLogService.info('ChatPage', '无活跃对话，创建新对话');
        ref.read(conversationsProvider.notifier).createConversation();
        convId = ref.read(activeConversationIdProvider);
        await AppLogService.info('ChatPage', '新对话创建完成: $convId');
      }
      if (convId == null) return;
      // 登记在 convId 解析**之后**（含新建对话路径）：否则无活跃对话
      // 时两次极速回车都不会被 pending 拦截，第二条消息已入库却在
      // _startStreaming 的流式守卫处被静默丢弃（孤儿消息）。
      if (_pendingSendConvIds.contains(convId)) return;
      _pendingSendConvIds.add(convId);

      // 附件归属当前对话：图片压缩磁盘缓存按（对话, 哈希）隔离存储，
      // 发送前必须登记（选中时对话可能尚未创建）。若归属发生变化
      // （切换活跃对话后发送），清除"已落盘"标记——旧对话目录下的
      // 缓存作废，发送路径会在新对话下重新落盘（零等待保证不失效）。
      for (final att in attachments) {
        if (att.conversationId != convId) {
          att.conversationId = convId;
          att.compressedCachePersisted = false;
        }
      }

      await _ensureHistoryLoaded(convId);
      if (!mounted || ref.read(activeConversationIdProvider) != convId) return;

      // Save the current enabled tools to the conversation before sending.
      // This ensures the tool preferences are persisted even if the user
      // switches conversations or navigates away during streaming.
      _saveEnabledToolsToConversation();

      final userMsgId = 'u${DateTime.now().microsecondsSinceEpoch}';

      _history.add(
        ChatMessage(
          role: 'user',
          content: text,
          id: userMsgId,
          attachments: attachments,
        ),
      );
      await _controller?.insertMessage(
        Message.text(
          id: userMsgId,
          authorId: _currentUser.id,
          text: text,
          createdAt: DateTime.now(),
        ),
      );

      // Persist the user message before starting the background stream. If the
      // page is disposed during generation, the next page instance can load
      // this message even before the manager's periodic partial save runs.
      final historyForStream = List<ChatMessage>.from(_history);
      final saveFuture = _saveMessages(capturedConvId: convId);

      await _startStreaming(
        text,
        capturedConvId: convId,
        historyOverride: historyForStream,
      );
      await saveFuture;

      // Reload _history from conversation provider to ensure it reflects the
      // manager's persisted messages. Post-stream code in _startStreaming may
      // not execute reliably if the widget was disposed or an async error
      // occurred during background streaming.
      await _syncHistoryFromProvider(capturedConvId: convId);

      try {
        await AppLogService.info('ChatPage',
            '[STREAM-SEND] _onMessageSend: after sync, _history.length=${_history.length}');
      } catch (_) {}
    } finally {
      if (convId != null) _pendingSendConvIds.remove(convId);
    }
  }
}
