part of 'chat_stream_manager.dart';

extension _ChatStreamManagerTitleExt on ChatStreamManager {
  // ── 自动标题（title agent） ──────────────────────────────────────

  /// 用标题助手为对话生成标题。
  ///
  /// 仅当对话标题是自动生成的（[Conversation.titleAutoGenerated]，
  /// 即用户未手动改过）且已有用户消息时执行。失败静默返回，
  /// 保留截断标题作为兜底。
  ///
  /// 由 startStreaming 尾部 fire-and-forget 调用，绝不能被 await 阻塞
  /// 结果返回（见 startStreaming 中 complete 前的注释）。
  Future<void> _maybeGenerateTitle({
    required String convId,
    required List<ChatMessage> history,
  }) async {
    try {
      final ref = _ref;
      if (ref == null) return;

      final conv = ref
          .read(conversationsProvider)
          .where((c) => c.id == convId)
          .firstOrNull;
      if (conv == null || !conv.titleAutoGenerated) return;
      final firstUser = history.where((m) => m.role == 'user').firstOrNull;
      // 用最近一条用户消息生成/更新标题（标题随对话演进；
      // 若用首条消息，标题永远不更新）
      final lastUser = history.lastWhere(
        (m) => m.role == 'user' && m.content.trim().isNotEmpty,
        orElse: () => firstUser ?? history.first,
      );
      if (lastUser.content.trim().isEmpty) return;

      // 解析标题助手（默认内置；用户可替换）
      final settings = ref.read(systemAssistantSettingsProvider);
      final userAssistants = ref.read(assistantProvider);
      final titlePrompt = resolveSystemAssistantPrompt(
        assistantId: settings.titleAssistantId,
        userAssistants: userAssistants,
      );
      if (titlePrompt == null) return;

      final svc = _adapter.createTransientService();
      if (svc == null) return;

      // 标题请求是真实 API 请求（每次发送都会产生），其 cost 同样是
      // 该对话的计费事实：usage 数据返回后立即累加（事件驱动、
      // per-request 隔离，不会与主请求张冠李戴）。输入/输出计量不写入
      // （标题输入仅一条消息，写入会污染上下文显示与压缩触发判断）。
      svc.onUsageEvent = (usage, {required bool recordInput}) {
        _commitUsage(convId, usage, recordInput: recordInput);
      };

      String title;
      try {
        title = await svc.sendPrompt(
          systemPrompt: titlePrompt,
          // 标题任务只需最近一条用户消息文本，剥离附件避免重新读取大文件
          history: [lastUser.copyWith(attachments: [])],
          maxTokens: 200,
          // 事件驱动下并发读取共享 usage 槽的风险已不存在（per-request
          // 隔离）；标题请求计费随 usage 事件立即累加（recordInputTokens:
          // false → 只累计 cost，不写 tokens）
          accumulateUsage: true,
          recordInputTokens: false,
        );
      } catch (e) {
        debugPrint('[ChatStreamManager] 标题生成请求失败: $e');
        return;
      }
      // 清理：单行、去引号、截断 50 字符
      var cleaned = title.replaceAll('\n', ' ').trim();
      cleaned = cleaned.replaceAll(RegExp(r'^["“”「」]+|["“”「」]+$'), '');
      cleaned = cleaned.trim();
      if (cleaned.isEmpty) return;
      if (cleaned.length > 50) cleaned = cleaned.substring(0, 50);

      // 保持 titleAutoGenerated=true：对话演进后可再次自动更新标题
      // （手动改名走 renameConversation 置 false，不再覆盖）
      // TOCTOU 防护：标题 LLM 往返期间（秒级）用户可能已手动改名
      // （renameConversation 置 false）——提交前重读对话复查，
      // 用户手动改名绝不能被 AI 标题覆盖。
      final latest = ref
          .read(conversationsProvider)
          .where((c) => c.id == convId)
          .firstOrNull;
      if (latest == null || !latest.titleAutoGenerated) return;
      await ref
          .read(conversationsProvider.notifier)
          .updateTitle(convId, cleaned);
      await AppLogService.info(
          'ChatStreamManager', '[TITLE] 自动标题生成完成: $cleaned');
    } catch (e) {
      // fire-and-forget 路径：任何异常都静默，避免 unhandled async error
      debugPrint('[ChatStreamManager] 自动标题失败: $e');
    }
  }
}
