part of 'conversation_provider.dart';
// Extension methods on the State class cannot use @protected members
// (setState / state) without analyzer warnings, but the receiver IS the
// State/StateNotifier, so runtime behavior is identical to the original
// inline code.
// ignore_for_file: invalid_use_of_protected_member, invalid_use_of_visible_for_testing_member

extension ConversationsNotifierMutationsExt on ConversationsNotifier {
  // --------------------------------------------------------------------------
  // Mutations
  // --------------------------------------------------------------------------

  /// Creates a new conversation with an empty title, adds it to the list,
  /// and sets it as the active conversation.
  ///
  /// 不在此处持久化（避免与后续 updateMessages 的持久化竞争），
  /// 由 chat_provider 的 listener 负责持久化带消息的状态。
  String createConversation({String? assistantId}) {
    final now = DateTime.now();
    final conv = Conversation(
      title: '',
      createdAt: now,
      updatedAt: now,
      messages: [],
      assistantId: assistantId,
    );
    state = [conv, ...state];
    _ref.read(activeConversationIdProvider.notifier).state = conv.id;
    _persistActiveId();
    return conv.id;
  }

  /// Deletes a conversation by [id]. If it was the active conversation, clears
  /// the active selection.
  Future<void> deleteConversation(String id) async {
    state = state.where((c) => c.id != id).toList();
    if (_ref.read(activeConversationIdProvider) == id) {
      _ref.read(activeConversationIdProvider.notifier).state = null;
    }
    await _persist();
    await _persistActiveId();
  }

  /// Selects a conversation by [id], setting it as the active one.
  void selectConversation(String id) {
    _ref.read(activeConversationIdProvider.notifier).state = id;
    _persistActiveId();
  }

  /// Renames a conversation.
  /// 手动改名会清除自动生成标记（AI 标题不再覆盖）。
  Future<void> renameConversation(String id, String title) async {
    state = state.map((c) {
      if (c.id != id) return c;
      c.title = title;
      c.titleAutoGenerated = false;
      c.updatedAt = DateTime.now();
      return c;
    }).toList();
    await _persist();
  }

  /// 用 AI 标题助手更新标题（保持 [Conversation.titleAutoGenerated]，
  /// 对话演进后可再次自动更新；手动改名请走 [renameConversation]）。
  Future<void> updateTitle(String id, String title) async {
    state = state.map((c) {
      if (c.id != id) return c;
      c.title = title;
      c.updatedAt = DateTime.now();
      return c;
    }).toList();
    await _persist();
  }

  /// Toggles the pinned state of a conversation.
  /// Does NOT modify [updatedAt] — pinning is a metadata operation that should
  /// preserve the conversation's original last-updated time.
  void togglePin(String id) {
    state = state.map((c) {
      if (c.id != id) return c;
      c.isPinned = !c.isPinned;
      return c;
    }).toList();
    _persist();
  }

  /// Reorders a conversation from [oldIndex] to [newIndex] in the list.
  void reorderConversation(int oldIndex, int newIndex) {
    final list = [...state];
    final item = list.removeAt(oldIndex);
    list.insert(newIndex, item);
    state = list;
    _persist();
  }

  /// Deletes multiple conversations by [ids]. Also clears active if included.
  Future<void> batchDelete(List<String> ids) async {
    final idSet = ids.toSet();
    state = state.where((c) => !idSet.contains(c.id)).toList();
    if (idSet.contains(_ref.read(activeConversationIdProvider))) {
      _ref.read(activeConversationIdProvider.notifier).state = null;
    }
    await _persist();
    await _persistActiveId();
  }

  /// Auto-generates a title for a conversation using the first messages.
  /// 生成的标题标记为自动生成（AI 标题助手可覆盖）。
  Future<void> autoRenameConversation(String id) async {
    final conv = state.where((c) => c.id == id).firstOrNull;
    if (conv == null || conv.messages.isEmpty) return;

    final firstUser = conv.messages.firstWhere(
      (m) => m.role == 'user',
      orElse: () => conv.messages.first,
    );
    final firstAssistant =
        conv.messages.where((m) => m.role == 'assistant').firstOrNull;

    String combined = firstUser.content;
    if (firstAssistant != null) {
      combined += ' - ${firstAssistant.content}';
    }
    final title =
        combined.length > 60 ? '${combined.substring(0, 60)}…' : combined;

    state = state.map((c) {
      if (c.id != id) return c;
      c.title = title;
      c.titleAutoGenerated = true;
      c.updatedAt = DateTime.now();
      return c;
    }).toList();
    await _persist();
  }

  /// Replaces the message list of a conversation (e.g. after sending or
  /// loading a different conversation).
  Future<void> updateMessages(
      String conversationId, List<ChatMessage> messages) async {
    state = state.map((c) {
      if (c.id != conversationId) return c;
      c.messages = messages;
      c.updatedAt = DateTime.now();
      // Derive title from the conversation overview if title is empty.
      if (c.title.isEmpty && messages.isNotEmpty) {
        final firstUser = messages.firstWhere(
          (m) => m.role == 'user',
          orElse: () => messages.first,
        );
        final firstAssistant =
            messages.where((m) => m.role == 'assistant').firstOrNull;

        String combined = firstUser.content;
        if (firstAssistant != null) {
          combined += ' - ${firstAssistant.content}';
        }
        c.title =
            combined.length > 60 ? '${combined.substring(0, 60)}…' : combined;
        // 标记为自动生成：流完成后由标题助手用 AI 标题覆盖
        c.titleAutoGenerated = true;
      }
      return c;
    }).toList();
    await _persistNow();
  }

  /// Saves the draft text for a specific conversation.
  ///
  /// Drafts are per-conversation and persisted along with the conversation
  /// data. When [draftText] is empty, the draft is cleared.
  void saveDraft(String conversationId, String draftText) {
    state = state.map((c) {
      if (c.id != conversationId) return c;
      c.draftText = draftText;
      return c;
    }).toList();
    _persist();
  }

  /// Updates the enabled MCP/built-in tool names for a conversation.
  /// These are the tools the user has turned ON for this specific conversation.
  /// Also marks the conversation as having an explicit tool selection so the
  /// chat page won't auto-enable all tools on next load (preserves the
  /// "user toggled every tool off" case).
  void updateEnabledTools(String conversationId, Set<String> enabledTools) {
    state = state.map((c) {
      if (c.id != conversationId) return c;
      c.enabledMcpToolNames = Set<String>.from(enabledTools);
      c.hasExplicitEnabledMcpTools = true;
      return c;
    }).toList();
    _persist();
  }

  /// Updates the last used model name for a conversation.
  /// This is used to restore the model when re-entering the conversation.
  void updateLastUsedModel(String conversationId, String modelName) {
    state = state.map((c) {
      if (c.id != conversationId) return c;
      c.lastUsedModelName = modelName;
      return c;
    }).toList();
    _persist();
  }

  /// 更新对话的实际 token 计量与累计花费。
  ///
  /// [inputTokens]/[outputTokens] 来自 API 返回的 usage（非估算）；
  /// [costIncrement] 为 API 返回的本次请求花费（如 OpenRouter
  /// usage.total_cost），累加到 [Conversation.totalCost]。
  Future<void> updateUsage({
    required String conversationId,
    int? inputTokens,
    int? outputTokens,
    double costIncrement = 0,
  }) async {
    state = state.map((c) {
      if (c.id != conversationId) return c;
      if (inputTokens != null) c.lastInputTokens = inputTokens;
      if (outputTokens != null) c.lastOutputTokens = outputTokens;
      if (costIncrement > 0) c.totalCost += costIncrement;
      c.updatedAt = DateTime.now();
      return c;
    }).toList();
    await _persist();
  }

  /// Updates the context compaction summary for a conversation.
  Future<void> updateContextSummary(String conversationId, String summary,
      {String? tailStartId}) async {
    state = state.map((c) {
      if (c.id != conversationId) return c;
      c.contextSummary = summary;
      // 记录尾部起点消息 ID（prune 边界，对齐 opencode tail_start_id）
      if (tailStartId != null) c.compactionTailStartId = tailStartId;
      c.updatedAt = DateTime.now();
      return c;
    }).toList();
    await _persist();
  }
}
