part of 'conversation_provider.dart';
// Extension methods on the State class cannot use @protected members
// (setState / state) without analyzer warnings, but the receiver IS the
// State/StateNotifier, so runtime behavior is identical to the original
// inline code.
// ignore_for_file: invalid_use_of_protected_member, invalid_use_of_visible_for_testing_member

extension ConversationsNotifierMutationsExt on ConversationsNotifier {
  // --------------------------------------------------------------------------
  // Mutations
  // --------------------------------------------------------------------------

  /// Creates a new conversation with an empty title, adds it to the list,
  /// and sets it as the active conversation.
  ///
  /// When [assistantId] points to an existing assistant, the NEW conversation
  /// is seeded with the assistant's conversation defaults:
  /// - [Assistant.defaultToolNames] (non-null = the user configured the
  ///   defaults tab) becomes the conversation's explicit enabled-tool set,
  ///   with [Conversation.hasExplicitEnabledMcpTools] set — so tools NOT in
  ///   the default set stay OFF instead of being auto-enabled. An assistant
  ///   whose defaults were never configured (null set) keeps the legacy
  ///   behavior (new topics auto-enable all tools). A per-conversation
  ///   override made later in the chat page persists independently and
  ///   never affects other conversations.
  /// - [Assistant.defaultModelName] is pre-recorded as the conversation's
  ///   last-used model, so the chat page restores it on first entry (and the
  ///   user's later model switches stay per-conversation).
  ///
  /// Conversations created WITHOUT an assistant keep the legacy behavior:
  /// no explicit tool prefs (chat page auto-enables all tools) and no model
  /// preset (global saved selection applies).
  ///
  /// 立即持久化（_persistNow）：空对话在未发消息前被杀进程即永久丢失；
  /// _persistCore 的 _loadHasRun 守卫保证启动窗口内不覆写磁盘，
  /// _load 完成时会把内存新对话合并落盘。
  String createConversation({String? assistantId}) {
    final now = DateTime.now();
    final assistant = assistantId == null
        ? null
        : _ref
            .read(assistantProvider)
            .where((a) => a.id == assistantId)
            .firstOrNull;
    final hasToolDefaults = assistant?.defaultToolNames != null;
    final conv = Conversation(
      title: '',
      createdAt: now,
      updatedAt: now,
      messages: [],
      assistantId: assistantId,
      enabledMcpToolNames: hasToolDefaults
          ? Set<String>.from(assistant!.defaultToolNames!)
          : null,
      hasExplicitEnabledMcpTools: hasToolDefaults,
      lastUsedModelName: assistant?.defaultModelName,
      lastUsedModelId: assistant?.defaultModelId,
      lastUsedProviderName: assistant?.defaultProviderName,
    );
    state = [conv, ...state];
    _ref.read(activeConversationIdProvider.notifier).state = conv.id;
    _persistActiveId();
    // 立即持久化新对话（_persistNow 而非防抖 _persist）：空对话在
    // 未发消息前被杀进程即永久丢失；防抖还会在测试/快速连续创建时
    // 留下 pending timer。
    _persistNow();
    return conv.id;
  }

  /// Deletes a conversation by [id]. If it was the active conversation, clears
  /// the active selection.
  Future<void> deleteConversation(String id) async {
    state = state.where((c) => c.id != id).toList();
    if (_ref.read(activeConversationIdProvider) == id) {
      _ref.read(activeConversationIdProvider.notifier).state = null;
    }
    await _persist();
    await _persistActiveId();
  }

  /// Selects a conversation by [id], setting it as the active one.
  void selectConversation(String id) {
    _ref.read(activeConversationIdProvider.notifier).state = id;
    _persistActiveId();
  }

  /// Renames a conversation.
  /// 手动改名会清除自动生成标记（AI 标题不再覆盖）。
  Future<void> renameConversation(String id, String title) async {
    state = state.map((c) {
      if (c.id != id) return c;
      c.title = title;
      c.titleAutoGenerated = false;
      c.updatedAt = DateTime.now();
      return c;
    }).toList();
    await _persist();
  }

  /// 用 AI 标题助手更新标题（保持 [Conversation.titleAutoGenerated]，
  /// 对话演进后可再次自动更新；手动改名请走 [renameConversation]）。
  Future<void> updateTitle(String id, String title) async {
    state = state.map((c) {
      if (c.id != id) return c;
      c.title = title;
      c.updatedAt = DateTime.now();
      return c;
    }).toList();
    await _persist();
  }

  /// Toggles the pinned state of a conversation.
  /// Does NOT modify [updatedAt] — pinning is a metadata operation that should
  /// preserve the conversation's original last-updated time.
  void togglePin(String id) {
    state = state.map((c) {
      if (c.id != id) return c;
      c.isPinned = !c.isPinned;
      return c;
    }).toList();
    _persist();
  }

  /// Reorders a conversation from [oldIndex] to [newIndex] in the list.
  void reorderConversation(int oldIndex, int newIndex) {
    final list = [...state];
    final item = list.removeAt(oldIndex);
    list.insert(newIndex, item);
    state = list;
    _persist();
  }

  /// Deletes multiple conversations by [ids]. Also clears active if included.
  Future<void> batchDelete(List<String> ids) async {
    final idSet = ids.toSet();
    state = state.where((c) => !idSet.contains(c.id)).toList();
    if (idSet.contains(_ref.read(activeConversationIdProvider))) {
      _ref.read(activeConversationIdProvider.notifier).state = null;
    }
    await _persist();
    await _persistActiveId();
  }

  /// Auto-generates a title for a conversation using the first messages.
  /// 生成的标题标记为自动生成（AI 标题助手可覆盖）。
  Future<void> autoRenameConversation(String id) async {
    final conv = state.where((c) => c.id == id).firstOrNull;
    if (conv == null || conv.messages.isEmpty) return;

    final firstUser = conv.messages.firstWhere(
      (m) => m.role == 'user',
      orElse: () => conv.messages.first,
    );
    final firstAssistant =
        conv.messages.where((m) => m.role == 'assistant').firstOrNull;

    String combined = firstUser.content;
    if (firstAssistant != null) {
      combined += ' - ${firstAssistant.content}';
    }
    final title =
        combined.length > 60 ? '${combined.substring(0, 60)}…' : combined;

    state = state.map((c) {
      if (c.id != id) return c;
      c.title = title;
      c.titleAutoGenerated = true;
      c.updatedAt = DateTime.now();
      return c;
    }).toList();
    await _persist();
  }

  /// Replaces the message list of a conversation (e.g. after sending or
  /// loading a different conversation).
  Future<void> updateMessages(
      String conversationId, List<ChatMessage> messages) async {
    state = state.map((c) {
      if (c.id != conversationId) return c;
      c.messages = messages;
      c.updatedAt = DateTime.now();
      // Derive title from the conversation overview if title is empty.
      if (c.title.isEmpty && messages.isNotEmpty) {
        final firstUser = messages.firstWhere(
          (m) => m.role == 'user',
          orElse: () => messages.first,
        );
        final firstAssistant =
            messages.where((m) => m.role == 'assistant').firstOrNull;

        String combined = firstUser.content;
        if (firstAssistant != null) {
          combined += ' - ${firstAssistant.content}';
        }
        c.title =
            combined.length > 60 ? '${combined.substring(0, 60)}…' : combined;
        // 标记为自动生成：流完成后由标题助手用 AI 标题覆盖
        c.titleAutoGenerated = true;
      }
      return c;
    }).toList();
    await _persistNow();
  }

  /// Saves the draft (text + unsent attachment snapshots) for a specific
  /// conversation.
  ///
  /// Drafts are per-conversation and persisted along with the conversation
  /// data. When [draftText] is empty and [draftAttachments] is empty, the
  /// draft is cleared.
  void saveDraft(
    String conversationId,
    String draftText, {
    List<Attachment>? draftAttachments,
  }) {
    state = state.map((c) {
      if (c.id != conversationId) return c;
      c.draftText = draftText;
      if (draftAttachments != null) {
        // composer 传入的是快照副本（toMap/fromMap 深拷贝），与
        // pending 列表无引用共享——后续预压缩/编辑不会污染草稿。
        c.draftAttachments = draftAttachments;
      }
      return c;
    }).toList();
    _persist();
  }

  /// Updates the enabled MCP/built-in tool names for a conversation.
  /// These are the tools the user has turned ON for this specific conversation.
  /// Also marks the conversation as having an explicit tool selection so the
  /// chat page won't auto-enable all tools on next load (preserves the
  /// "user toggled every tool off" case).
  void updateEnabledTools(String conversationId, Set<String> enabledTools) {
    state = state.map((c) {
      if (c.id != conversationId) return c;
      c.enabledMcpToolNames = Set<String>.from(enabledTools);
      c.hasExplicitEnabledMcpTools = true;
      return c;
    }).toList();
    _persist();
  }

  /// Updates the last used model for a conversation.
  /// This is used to restore the model when re-entering the conversation.
  ///
  /// [modelName] 是显示名（用于兼容旧数据与显示），[modelId] 是 API 模型
  /// ID、[providerName] 是供应商名——两者构成绝对身份，模型/供应商被
  /// 重命名后该对话记录仍能解析回同一模型。
  void updateLastUsedModel(
    String conversationId,
    String modelName, {
    String? modelId,
    String? providerName,
  }) {
    state = state.map((c) {
      if (c.id != conversationId) return c;
      c.lastUsedModelName = modelName;
      c.lastUsedModelId = modelId;
      c.lastUsedProviderName = providerName;
      return c;
    }).toList();
    _persist();
  }

  /// 更新对话的实际 token 计量与累计花费。
  ///
  /// [inputTokens]/[outputTokens] 来自 API 返回的 usage（非估算）；
  /// [costIncrement] 为 API 返回的本次请求花费（如 OpenRouter
  /// usage.total_cost），累加到 [Conversation.totalCost]。
  Future<void> updateUsage({
    required String conversationId,
    int? inputTokens,
    int? outputTokens,
    double costIncrement = 0,
  }) async {
    state = state.map((c) {
      if (c.id != conversationId) return c;
      if (inputTokens != null) c.lastInputTokens = inputTokens;
      if (outputTokens != null) c.lastOutputTokens = outputTokens;
      if (costIncrement > 0) c.totalCost += costIncrement;
      c.updatedAt = DateTime.now();
      return c;
    }).toList();
    await _persist();
  }

  /// Updates the context compaction summary for a conversation.
  Future<void> updateContextSummary(String conversationId, String summary,
      {String? tailStartId}) async {
    state = state.map((c) {
      if (c.id != conversationId) return c;
      c.contextSummary = summary;
      // 记录尾部起点消息 ID（prune 边界，对齐 opencode tail_start_id）
      if (tailStartId != null) c.compactionTailStartId = tailStartId;
      c.updatedAt = DateTime.now();
      return c;
    }).toList();
    await _persist();
  }
}
