part of 'chat_agent_semantics_test.dart';

void chatAgentSemanticsGroup3() {
  group('自动标题', () {
    test('流完成后用标题助手生成 AI 标题', () async {
      final container = _makeContainer(
        conversations: [Conversation(id: 'conv-title', title: '')],
      );
      final manager = container.read(chatStreamManagerProvider);

      // 调用顺序：主请求 → 标题生成（单条用户消息无旧历史可压缩，
      // head 为空 → 压缩不触发）
      final provider = _RecordingProvider([
        [AIStreamEvent('回答')],
        [AIStreamEvent('「AI 生成的标题」')],
      ]);
      manager.adapter.forceService(_makeService(provider));

      await manager.startStreaming(
        text: '帮我优化代码',
        convId: 'conv-title',
        history: [ChatMessage(role: 'user', content: '帮我优化代码')],
      );

      // 标题生成是 fire-and-forget（不阻塞结果返回），等待其完成
      await _waitFor(() => provider.captures.length >= 2);
      expect(provider.captures, hasLength(2));
      // 标题请求使用内置标题助手 prompt（OpenAI：system 消息）
      final titleSys = (provider.captures[1]['messages'] as List)
          .cast<Map>()
          .where((m) => m['role'] == 'system')
          .toList();
      expect(titleSys, isNotEmpty);
      expect(titleSys.first['content'], contains('标题生成器'));
      // 标题已更新（去引号）
      final conv = container
          .read(conversationsProvider)
          .where((c) => c.id == 'conv-title')
          .first;
      expect(conv.title, 'AI 生成的标题');
      expect(conv.titleAutoGenerated, isTrue, reason: 'AI 标题后保持自动标记，对话演进可再次更新');
      container.dispose();
    });

    test('用户手动改过标题时不覆盖', () async {
      final container = _makeContainer(
        conversations: [
          Conversation(id: 'conv-manual', title: '我的手动标题'),
        ],
      );
      final manager = container.read(chatStreamManagerProvider);
      final provider = _RecordingProvider([
        [AIStreamEvent('回答')],
      ]);
      manager.adapter.forceService(ChatService(
        provider: provider,
        modelConfig: _createModelConfig(context: 1000000),
      ));

      await manager.startStreaming(
        text: 'hi',
        convId: 'conv-manual',
        history: [ChatMessage(role: 'user', content: 'hi')],
      );

      // 标题请求未发生（仅主请求）
      expect(provider.captures, hasLength(1));
      final conv = container
          .read(conversationsProvider)
          .where((c) => c.id == 'conv-manual')
          .first;
      expect(conv.title, '我的手动标题');
      container.dispose();
    });
  });

  group('工具结果截断', () {
    test('存储完整（50KB 内不截断），发送给模型时按设置渲染截断', () async {
      final provider = _RecordingProvider([
        [
          AIStreamEvent('', toolCalls: [
            {
              'id': 'call_big',
              'type': 'function',
              'function': {
                'name': 'big_tool',
                'arguments': '{}',
              },
            },
          ]),
        ],
        [AIStreamEvent('done')],
      ]);
      final service = _makeService(provider);
      // 助手配置截断上限 2000 字符：发送渲染按此截断（存储仍完整）。
      service.setAssistantSettings(AssistantSettings(
        maxToolOutputChars: 2000,
        enableMaxToolOutputChars: true,
      ));
      ChatService.registerTool(
        const ToolDefinition(
          name: 'big_tool',
          description: 'big',
          parameters: {'type': 'object'},
        ),
        // 5000 字符 < 50KB 存储上限：完整保留（opencode MAX_BYTES 语义）
        (args) => 'x' * 5000,
      );

      final events = <ChatEvent>[];
      await service
          .sendStreamWithTools(
            'go',
            history: [ChatMessage(role: 'user', content: 'go')],
            tools: ChatService.getRegisteredToolDefinitions(),
          )
          .listen(events.add, onError: (e) => fail('error: $e'))
          .asFuture();

      // 存储/事件结果完整（5000 字符全部保留）
      final complete = events.whereType<ToolCallCompleteEvent>().single;
      expect(complete.result, 'x' * 5000);

      // 链中 tool 消息：发送给模型时渲染截断至助手配置的 2000 字符
      final toolMsg = (provider.captures[1]['messages'] as List)
          .cast<Map>()
          .where((m) => m['role'] == 'tool')
          .single;
      expect(toolMsg['content'], startsWith('x' * 2000));
      expect(toolMsg['content'], contains('[已截断]'));
      expect((toolMsg['content'] as String).length, lessThan(5000));
    });

    test('关闭截断开关：完整发送存储的工具结果（不追加截断后缀）', () async {
      final provider = _RecordingProvider([
        [
          AIStreamEvent('', toolCalls: [
            {
              'id': 'call_full',
              'type': 'function',
              'function': {
                'name': 'full_tool',
                'arguments': '{}',
              },
            },
          ]),
        ],
        [AIStreamEvent('done')],
      ]);
      final service = _makeService(provider);
      // 关闭截断：即使结果远超默认 5000 字符也完整发送。
      service.setAssistantSettings(AssistantSettings(
        enableMaxToolOutputChars: false,
      ));
      ChatService.registerTool(
        const ToolDefinition(
          name: 'full_tool',
          description: 'full',
          parameters: {'type': 'object'},
        ),
        (args) => 'y' * 8000,
      );

      final events = <ChatEvent>[];
      await service
          .sendStreamWithTools(
            'go',
            history: [ChatMessage(role: 'user', content: 'go')],
            tools: ChatService.getRegisteredToolDefinitions(),
          )
          .listen(events.add, onError: (e) => fail('error: $e'))
          .asFuture();

      final toolMsg = (provider.captures[1]['messages'] as List)
          .cast<Map>()
          .where((m) => m['role'] == 'tool')
          .single;
      expect(toolMsg['content'], 'y' * 8000,
          reason: '关闭截断时完整发送（仍受 50KB 存储上限约束）');
    });

    test('默认上限 5000 字符，CJK 按字符计（非字节）', () async {
      final provider = _RecordingProvider([
        [
          AIStreamEvent('', toolCalls: [
            {
              'id': 'call_cjk',
              'type': 'function',
              'function': {
                'name': 'cjk_tool',
                'arguments': '{}',
              },
            },
          ]),
        ],
        [AIStreamEvent('done')],
      ]);
      // 无助手设置（默认路径）：截断上限 = 5000 字符。
      final service = _makeService(provider);
      // 4000 个中文字符 = 12000 UTF-8 字节：若按旧版 2K 字节截断会
      // 被砍，按字符计（4000 < 5000）则完整保留。
      ChatService.registerTool(
        const ToolDefinition(
          name: 'cjk_tool',
          description: 'cjk',
          parameters: {'type': 'object'},
        ),
        (args) => '中' * 4000,
      );

      final events = <ChatEvent>[];
      await service
          .sendStreamWithTools(
            'go',
            history: [ChatMessage(role: 'user', content: 'go')],
            tools: ChatService.getRegisteredToolDefinitions(),
          )
          .listen(events.add, onError: (e) => fail('error: $e'))
          .asFuture();

      final toolMsg = (provider.captures[1]['messages'] as List)
          .cast<Map>()
          .where((m) => m['role'] == 'tool')
          .single;
      expect(toolMsg['content'], '中' * 4000,
          reason: '截断单位是字符：4000 个 CJK 字符（12000 字节）在 5000 字符上限内不截断');
    });

    test('超过 50KB 存储上限才截断（对齐 opencode MAX_BYTES）', () async {
      final provider = _RecordingProvider([
        [
          AIStreamEvent('', toolCalls: [
            {
              'id': 'call_huge',
              'type': 'function',
              'function': {
                'name': 'huge_tool',
                'arguments': '{}',
              },
            },
          ]),
        ],
        [AIStreamEvent('done')],
      ]);
      final service = _makeService(provider);
      ChatService.registerTool(
        const ToolDefinition(
          name: 'huge_tool',
          description: 'huge',
          parameters: {'type': 'object'},
        ),
        (args) => 'x' * 60000, // > 50KB
      );

      final events = <ChatEvent>[];
      await service
          .sendStreamWithTools(
            'go',
            history: [ChatMessage(role: 'user', content: 'go')],
            tools: ChatService.getRegisteredToolDefinitions(),
          )
          .listen(events.add, onError: (e) => fail('error: $e'))
          .asFuture();

      final complete = events.whereType<ToolCallCompleteEvent>().single;
      expect(complete.result.length, lessThan(60000));
      expect(complete.result, startsWith('x' * (50 * 1024)));
      expect(complete.result, contains('[已截断]'));
    });
  });

  group('sendPrompt（内部任务请求）', () {
    test('跳过推理与工具事件，只收集文本', () async {
      final provider = _RecordingProvider([
        [
          AIStreamEvent('思考中', isReasoning: true),
          AIStreamEvent('', toolCalls: [
            {'id': 'x', 'name': 't', 'input': {}},
          ]),
          AIStreamEvent('最终标题'),
        ],
      ]);
      final service = _makeService(provider);
      final result = await service.sendPrompt(
        systemPrompt: '你是标题生成器',
        history: [ChatMessage(role: 'user', content: '帮我优化')],
        maxTokens: 200,
      );
      expect(result, '最终标题');
      // 请求体：system 消息在前，无工具
      final msgs = (provider.captures[0]['messages'] as List).cast<Map>();
      expect(msgs.first['role'], 'system');
      expect(msgs.first['content'], '你是标题生成器');
      expect(provider.captures[0]['tools'], isNull);
    });
  });

  group('OpenAI 协议 system 合并', () {
    test('assistantPrompt 与 contextSummary 合并为单条 system 消息', () async {
      final provider = _RecordingProvider([
        [AIStreamEvent('ok')],
      ]);
      final service = _makeService(provider);
      service.setAssistantPrompt('你是助手');
      service.setContextSummary('旧对话摘要内容');
      await service
          .sendStream(
            'hi',
            history: [ChatMessage(role: 'user', content: 'hi')],
          )
          .listen((_) {})
          .asFuture();

      final msgs = (provider.captures[0]['messages'] as List).cast<Map>();
      final sysMsgs = msgs.where((m) => m['role'] == 'system').toList();
      expect(sysMsgs, hasLength(1), reason: '严格端点拒绝多条 system 消息');
      final content = sysMsgs.single['content'] as String;
      expect(content, contains('你是助手'));
      expect(content, contains('旧对话摘要内容'));
    });
  });

  group('titleAutoGenerated 序列化', () {
    test('toMap/fromMap 往返', () {
      final conv = Conversation(
        title: '自动标题',
        titleAutoGenerated: true,
      );
      final restored = Conversation.fromMap(conv.toMap());
      expect(restored.titleAutoGenerated, isTrue);
    });

    test('旧数据缺省 false（不覆盖手动标题语义）', () {
      final restored = Conversation.fromMap({
        'id': 'c1',
        'title': 't',
        'createdAt': DateTime.now().toIso8601String(),
        'updatedAt': DateTime.now().toIso8601String(),
        'messages': <dynamic>[],
      });
      expect(restored.titleAutoGenerated, isFalse);
    });
  });

  group('协议层换端点（ChatService 级）', () {
    test('anthropic 端点：请求走 Anthropic 协议（system 顶层 + 链格式）', () async {
      final provider = _RecordingProvider([
        [
          AIStreamEvent('', toolCalls: [
            {
              'id': 'toolu_1',
              'name': 'loop_tool',
              'input': {'i': 1}
            },
          ]),
        ],
        [AIStreamEvent('done')],
      ]);
      final service = _makeService(provider, endpointType: 'anthropic');
      expect(service.protocol, isA<AnthropicProtocol>());
      ChatService.registerTool(
        const ToolDefinition(
          name: 'loop_tool',
          description: 'loop',
          parameters: {'type': 'object'},
        ),
        (args) => 'ok',
      );

      await service
          .sendStreamWithTools(
            'go',
            history: [
              ChatMessage(role: 'user', content: 'go'),
              ChatMessage(role: 'assistant', content: '前一轮'),
            ],
            tools: ChatService.getRegisteredToolDefinitions(),
          )
          .listen((_) {})
          .asFuture();

      // 第 1 轮请求：system 走顶层字段（非 system 消息），
      // messages 只含 user/assistant
      final messages1 = (provider.captures[0]['messages'] as List).cast<Map>();
      expect(
          messages1.map((m) => m['role']), containsAll(['user', 'assistant']));
      expect(
        messages1.any((m) => m['role'] == 'system'),
        isFalse,
        reason: 'Anthropic 协议 system 不入 messages',
      );
      // 工具定义是 anthropic 形状（name/input_schema，无 function 包装）
      final tools = (provider.captures[0]['tools'] as List).cast<Map>();
      expect(tools.first.containsKey('function'), isFalse);
      expect(tools.first['name'], 'loop_tool');
      expect(tools.first['input_schema'], isNotNull);

      // 第 2 轮请求：链重建为 assistant(tool_use) + user(tool_result)
      final messages2 = (provider.captures[1]['messages'] as List).cast<Map>();
      final assistantMsg =
          messages2.where((m) => m['role'] == 'assistant').last;
      final contentBlocks = (assistantMsg['content'] as List).cast<Map>();
      expect(contentBlocks.any((b) => b['type'] == 'tool_use'), isTrue);
      final toolUse = contentBlocks.firstWhere((b) => b['type'] == 'tool_use');
      expect(toolUse['id'], 'toolu_1');
      expect(toolUse['name'], 'loop_tool');
      // tool_result 配对
      final userMsg = messages2.last;
      final userBlocks = (userMsg['content'] as List).cast<Map>();
      expect(userBlocks.single['type'], 'tool_result');
      expect(userBlocks.single['tool_use_id'], 'toolu_1');
      expect(userBlocks.single['content'], 'ok');
    });
  });
}
