import 'package:flutter/material.dart';

/// Construction and view tools offered by the 3D editor.
enum ConstructionTool {
  move,
  point,
  pyramid,
  cube,
  sphere,
  plane,
  intersectionCurve,
  unfoldNet,
  showHideLabels,
  showHideObject,
  deleteObject,
  viewDirection,
  intersectionPoint,
  midpoint,
  pointOnObject,
  attachDetachPoint,
  segment,
  fixedLengthSegment,
  line,
  ray,
  vector,
  polygon,
  regularPolygon,
  perpendicularLine,
  parallelLine,
  angleBisector,
  tangentLine,
  prism,
  tetrahedron,
  sphereByRadius,
  cone,
  cylinder,
  extrudeCone,
  extrudePrism,
  surfaceOfRevolution,
  generalPlane,
  parallelPlane,
  perpendicularPlane,
  circleAxisPoint,
  circleCenterNormalRadius,
  circleThreePoints,
  circle,
  arc,
  circumcircleArc,
  circularSector,
  circumcircleSector,
  ellipse,
  conic,
  parabola,
  hyperbola,
  locus,
  reflectionInPlane,
  centralSymmetry,
  rotation,
  translation,
  dilation,
  axialSymmetry,
  angle,
  distance,
  area,
  volume,
  rotateView,
  panView,
  copyStyle,
  text,
  equalVector,
  polyline,
  polarDiameter,
}

/// Categories in the 3D toolbox. Quick access tools can also appear in their
/// detailed category.
enum ToolGroup {
  basic('基本工具'),
  edit('编辑'),
  points('点'),
  lines('直线与多边形'),
  solids('立体图形'),
  planes('平面'),
  circles('圆'),
  curves('曲线'),
  transforms('变换'),
  measurement('度量'),
  other('其它'),
  specialLines('特殊直线');

  const ToolGroup(this.label);
  final String label;

  List<ConstructionTool> get tools => switch (this) {
    ToolGroup.basic => const [
      ConstructionTool.move,
      ConstructionTool.point,
      ConstructionTool.pyramid,
      ConstructionTool.cube,
      ConstructionTool.sphere,
      ConstructionTool.plane,
      ConstructionTool.intersectionCurve,
      ConstructionTool.unfoldNet,
    ],
    ToolGroup.edit => const [
      ConstructionTool.showHideLabels,
      ConstructionTool.showHideObject,
      ConstructionTool.deleteObject,
      ConstructionTool.viewDirection,
    ],
    ToolGroup.points => const [
      ConstructionTool.point,
      ConstructionTool.intersectionPoint,
      ConstructionTool.midpoint,
      ConstructionTool.pointOnObject,
      ConstructionTool.attachDetachPoint,
    ],
    ToolGroup.lines => const [
      ConstructionTool.segment,
      ConstructionTool.fixedLengthSegment,
      ConstructionTool.line,
      ConstructionTool.ray,
      ConstructionTool.vector,
      ConstructionTool.polygon,
      ConstructionTool.regularPolygon,
      ConstructionTool.perpendicularLine,
      ConstructionTool.parallelLine,
      ConstructionTool.angleBisector,
      ConstructionTool.tangentLine,
    ],
    ToolGroup.solids => const [
      ConstructionTool.pyramid,
      ConstructionTool.prism,
      ConstructionTool.tetrahedron,
      ConstructionTool.cube,
      ConstructionTool.sphere,
      ConstructionTool.sphereByRadius,
      ConstructionTool.cone,
      ConstructionTool.cylinder,
      ConstructionTool.extrudeCone,
      ConstructionTool.extrudePrism,
      ConstructionTool.unfoldNet,
      ConstructionTool.surfaceOfRevolution,
    ],
    ToolGroup.planes => const [
      ConstructionTool.plane,
      ConstructionTool.generalPlane,
      ConstructionTool.parallelPlane,
      ConstructionTool.perpendicularPlane,
    ],
    ToolGroup.circles => const [
      ConstructionTool.circleAxisPoint,
      ConstructionTool.circleCenterNormalRadius,
      ConstructionTool.circleThreePoints,
      ConstructionTool.circle,
      ConstructionTool.arc,
      ConstructionTool.circumcircleArc,
      ConstructionTool.circularSector,
      ConstructionTool.circumcircleSector,
    ],
    ToolGroup.curves => const [
      ConstructionTool.ellipse,
      ConstructionTool.conic,
      ConstructionTool.parabola,
      ConstructionTool.hyperbola,
      ConstructionTool.locus,
      ConstructionTool.intersectionCurve,
    ],
    ToolGroup.transforms => const [
      ConstructionTool.reflectionInPlane,
      ConstructionTool.centralSymmetry,
      ConstructionTool.rotation,
      ConstructionTool.translation,
      ConstructionTool.dilation,
      ConstructionTool.axialSymmetry,
    ],
    ToolGroup.measurement => const [
      ConstructionTool.angle,
      ConstructionTool.distance,
      ConstructionTool.area,
      ConstructionTool.volume,
    ],
    ToolGroup.other => const [
      ConstructionTool.rotateView,
      ConstructionTool.panView,
      ConstructionTool.copyStyle,
      ConstructionTool.text,
    ],
    ToolGroup.specialLines => const [
      ConstructionTool.equalVector,
      ConstructionTool.polyline,
      ConstructionTool.polarDiameter,
    ],
  };
}

enum ToolBehavior { construction, objectAction, command, navigation }

class ToolInfo {
  final ConstructionTool tool;
  final String name;
  final IconData iconData;
  final String tooltip;
  final ToolGroup group;
  final ToolBehavior behavior;
  final List<String> steps;

  const ToolInfo(
    this.tool,
    this.name,
    this.iconData,
    this.tooltip,
    this.group, {
    this.behavior = ToolBehavior.construction,
    this.steps = const [],
  });

  static const Map<ConstructionTool, ToolInfo> all = {
    ConstructionTool.move: ToolInfo(
      ConstructionTool.move,
      '移动',
      Icons.near_me_outlined,
      '拖动点移动对象；点击已选点切换平面/高度移动；空白处拖动旋转视图',
      ToolGroup.basic,
      behavior: ToolBehavior.navigation,
    ),
    ConstructionTool.point: ToolInfo(
      ConstructionTool.point,
      '描点',
      Icons.add_location_alt_outlined,
      '点击空间中的位置创建点；拖动设置高度；点击已选点切换平面/高度移动',
      ToolGroup.points,
      steps: ['点击位置创建点；拖动设置高度，点击已选点切换平面/高度移动'],
    ),
    ConstructionTool.pyramid: ToolInfo(
      ConstructionTool.pyramid,
      '棱锥',
      Icons.details_outlined,
      '选择底面顶点，再选择棱锥顶点',
      ToolGroup.solids,
      steps: ['选择底面第一个顶点', '选择底面第二个顶点', '选择底面第三个顶点', '选择棱锥顶点'],
    ),
    ConstructionTool.cube: ToolInfo(
      ConstructionTool.cube,
      '正六面体',
      Icons.view_in_ar_outlined,
      '选择一条棱的两个端点',
      ToolGroup.solids,
      steps: ['选择一条棱的第一个端点', '选择一条棱的第二个端点'],
    ),
    ConstructionTool.sphere: ToolInfo(
      ConstructionTool.sphere,
      '球面(球心与一点)',
      Icons.public,
      '选择球心和球面上一点',
      ToolGroup.solids,
      steps: ['选择球心', '选择球面上的一点'],
    ),
    ConstructionTool.plane: ToolInfo(
      ConstructionTool.plane,
      '三点平面',
      Icons.layers_outlined,
      '选择三个不共线的点',
      ToolGroup.planes,
      steps: ['选择第一个点', '选择第二个点', '选择第三个点'],
    ),
    ConstructionTool.intersectionCurve: ToolInfo(
      ConstructionTool.intersectionCurve,
      '相交曲线',
      Icons.device_hub,
      '依次选择两个相交的平面或球面',
      ToolGroup.curves,
      steps: ['选择第一个相交的平面或球面', '选择第二个相交的平面或球面'],
      behavior: ToolBehavior.objectAction,
    ),
    ConstructionTool.unfoldNet: ToolInfo(
      ConstructionTool.unfoldNet,
      '展开图',
      Icons.grid_view,
      '点击一个多面体生成展开图',
      ToolGroup.solids,
      steps: ['选择要展开的多面体'],
      behavior: ToolBehavior.objectAction,
    ),
    ConstructionTool.showHideLabels: ToolInfo(
      ConstructionTool.showHideLabels,
      '显示/隐藏标签',
      Icons.label_outline,
      '切换场景中对象标签的显示',
      ToolGroup.edit,
      behavior: ToolBehavior.command,
    ),
    ConstructionTool.showHideObject: ToolInfo(
      ConstructionTool.showHideObject,
      '显示/隐藏对象',
      Icons.visibility_outlined,
      '点击对象切换其显示状态',
      ToolGroup.edit,
      steps: ['选择要切换显示状态的对象'],
      behavior: ToolBehavior.objectAction,
    ),
    ConstructionTool.deleteObject: ToolInfo(
      ConstructionTool.deleteObject,
      '删除',
      Icons.delete_outline,
      '点击对象将其删除',
      ToolGroup.edit,
      steps: ['选择要删除的对象'],
      behavior: ToolBehavior.objectAction,
    ),
    ConstructionTool.viewDirection: ToolInfo(
      ConstructionTool.viewDirection,
      '视图方向',
      Icons.explore_outlined,
      '切换到标准等轴测视图',
      ToolGroup.edit,
      behavior: ToolBehavior.command,
    ),
    ConstructionTool.intersectionPoint: ToolInfo(
      ConstructionTool.intersectionPoint,
      '交点',
      Icons.device_hub,
      '选择两条相交直线、直线与平面/球面/曲线/立体，或相切的球面与平面/球面',
      ToolGroup.points,
      steps: ['选择第一个相交对象', '选择第二个相交对象'],
      behavior: ToolBehavior.objectAction,
    ),
    ConstructionTool.midpoint: ToolInfo(
      ConstructionTool.midpoint,
      '中点/中心',
      Icons.linear_scale,
      '选择两个点，创建它们的中点',
      ToolGroup.points,
      steps: ['选择第一个点', '选择第二个点'],
    ),
    ConstructionTool.pointOnObject: ToolInfo(
      ConstructionTool.pointOnObject,
      '对象上的点',
      Icons.place_outlined,
      '点击对象上的位置创建点',
      ToolGroup.points,
      steps: ['点击对象上的位置'],
    ),
    ConstructionTool.attachDetachPoint: ToolInfo(
      ConstructionTool.attachDetachPoint,
      '附着/脱离点',
      Icons.link,
      '点击点切换其附着状态',
      ToolGroup.points,
      steps: ['选择要切换附着状态的点'],
      behavior: ToolBehavior.objectAction,
    ),
    ConstructionTool.segment: ToolInfo(
      ConstructionTool.segment,
      '线段',
      Icons.horizontal_rule,
      '选择线段的两个端点',
      ToolGroup.lines,
      steps: ['选择线段起点', '选择线段终点'],
    ),
    ConstructionTool.fixedLengthSegment: ToolInfo(
      ConstructionTool.fixedLengthSegment,
      '定长线段',
      Icons.straighten,
      '依次选择起点、方向点和长度',
      ToolGroup.lines,
      steps: ['选择起点', '选择方向点', '选择长度'],
    ),
    ConstructionTool.line: ToolInfo(
      ConstructionTool.line,
      '直线',
      Icons.timeline,
      '选择直线上的两个点',
      ToolGroup.lines,
      steps: ['选择第一个点', '选择第二个点'],
    ),
    ConstructionTool.ray: ToolInfo(
      ConstructionTool.ray,
      '射线',
      Icons.trending_flat,
      '选择射线起点和方向点',
      ToolGroup.lines,
      steps: ['选择射线起点', '选择方向点'],
    ),
    ConstructionTool.vector: ToolInfo(
      ConstructionTool.vector,
      '向量',
      Icons.north_east,
      '选择向量起点和终点',
      ToolGroup.lines,
      steps: ['选择向量起点', '选择向量终点'],
    ),
    ConstructionTool.polygon: ToolInfo(
      ConstructionTool.polygon,
      '多边形',
      Icons.polyline_outlined,
      '依次选择顶点，再点击首点闭合',
      ToolGroup.lines,
      steps: ['选择多边形顶点', '继续选择顶点，点击首点闭合'],
    ),
    ConstructionTool.regularPolygon: ToolInfo(
      ConstructionTool.regularPolygon,
      '正多边形',
      Icons.hexagon_outlined,
      '设置边数，再选择一条边的两个端点',
      ToolGroup.lines,
      steps: ['选择边的第一个端点', '选择边的第二个端点'],
    ),
    ConstructionTool.perpendicularLine: ToolInfo(
      ConstructionTool.perpendicularLine,
      '垂线',
      Icons.vertical_align_center,
      '选择经过点和目标直线方向',
      ToolGroup.lines,
      steps: ['选择垂线经过点', '选择目标直线上的点', '选择目标直线方向点'],
    ),
    ConstructionTool.parallelLine: ToolInfo(
      ConstructionTool.parallelLine,
      '平行线',
      Icons.vertical_align_top,
      '选择经过点和方向线上的两点',
      ToolGroup.lines,
      steps: ['选择经过点', '选择方向线上的第一个点', '选择方向线上的第二个点'],
    ),
    ConstructionTool.angleBisector: ToolInfo(
      ConstructionTool.angleBisector,
      '角平分线',
      Icons.call_split,
      '选择角的两边点和顶点',
      ToolGroup.lines,
      steps: ['选择一边上的点', '选择角顶点', '选择另一边上的点'],
    ),
    ConstructionTool.tangentLine: ToolInfo(
      ConstructionTool.tangentLine,
      '切线',
      Icons.touch_app,
      '先点击曲线上的点，再点击圆或圆锥曲线生成切线',
      ToolGroup.lines,
      steps: ['选择曲线上的切点', '选择切线所依附的圆或圆锥曲线'],
      behavior: ToolBehavior.objectAction,
    ),
    ConstructionTool.prism: ToolInfo(
      ConstructionTool.prism,
      '棱柱',
      Icons.view_in_ar,
      '选择三角形底面和高度点',
      ToolGroup.solids,
      steps: ['选择底面第一个顶点', '选择底面第二个顶点', '选择底面第三个顶点', '选择高度点'],
    ),
    ConstructionTool.tetrahedron: ToolInfo(
      ConstructionTool.tetrahedron,
      '正四面体',
      Icons.change_history_outlined,
      '选择一条棱的两个端点',
      ToolGroup.solids,
      steps: ['选择一条棱的第一个端点', '选择一条棱的第二个端点'],
    ),
    ConstructionTool.sphereByRadius: ToolInfo(
      ConstructionTool.sphereByRadius,
      '球面(球心与半径)',
      Icons.public,
      '选择球心，再选择半径长度',
      ToolGroup.solids,
      steps: ['选择球心', '选择半径长度'],
    ),
    ConstructionTool.cone: ToolInfo(
      ConstructionTool.cone,
      '圆锥',
      Icons.change_history,
      '选择底面圆心、半径点和顶点',
      ToolGroup.solids,
      steps: ['选择底面圆心', '选择底面半径点', '选择圆锥顶点'],
    ),
    ConstructionTool.cylinder: ToolInfo(
      ConstructionTool.cylinder,
      '圆柱',
      Icons.storage_outlined,
      '选择底面圆心、半径点和顶面圆心',
      ToolGroup.solids,
      steps: ['选择底面圆心', '选择底面半径点', '选择顶面圆心'],
    ),
    ConstructionTool.extrudeCone: ToolInfo(
      ConstructionTool.extrudeCone,
      '拉成锥体',
      Icons.change_history,
      '选择底面圆心、半径点和高度点',
      ToolGroup.solids,
      steps: ['选择底面圆心', '选择底面半径点', '选择高度点'],
    ),
    ConstructionTool.extrudePrism: ToolInfo(
      ConstructionTool.extrudePrism,
      '拉成柱体',
      Icons.account_tree_outlined,
      '选择三角形底面和高度点',
      ToolGroup.solids,
      steps: ['选择底面第一个顶点', '选择底面第二个顶点', '选择底面第三个顶点', '选择高度点'],
    ),
    ConstructionTool.surfaceOfRevolution: ToolInfo(
      ConstructionTool.surfaceOfRevolution,
      '旋转曲面',
      Icons.rotate_right,
      '选择旋转轴两点和母线线段两端点',
      ToolGroup.solids,
      steps: ['选择旋转轴第一点', '选择旋转轴第二点', '选择母线第一点', '选择母线第二点'],
    ),
    ConstructionTool.generalPlane: ToolInfo(
      ConstructionTool.generalPlane,
      '平面',
      Icons.layers,
      '选择平面上一点和法向量端点',
      ToolGroup.planes,
      steps: ['选择平面上一点', '选择法向量端点'],
    ),
    ConstructionTool.parallelPlane: ToolInfo(
      ConstructionTool.parallelPlane,
      '平行平面',
      Icons.layers_outlined,
      '选择参考平面上的三点和新平面经过点',
      ToolGroup.planes,
      steps: ['选择参考平面第一个点', '选择参考平面第二个点', '选择参考平面第三个点', '选择新平面经过点'],
    ),
    ConstructionTool.perpendicularPlane: ToolInfo(
      ConstructionTool.perpendicularPlane,
      '垂直平面',
      Icons.layers,
      '选择参考平面上的三点、新平面经过点和方向点',
      ToolGroup.planes,
      steps: [
        '选择参考平面第一个点',
        '选择参考平面第二个点',
        '选择参考平面第三个点',
        '选择新平面经过点',
        '选择垂直平面方向点',
      ],
    ),
    ConstructionTool.circleAxisPoint: ToolInfo(
      ConstructionTool.circleAxisPoint,
      '圆(轴线与一点)',
      Icons.circle_outlined,
      '选择轴线两点和圆周上一点',
      ToolGroup.circles,
      steps: ['选择轴线第一点', '选择轴线第二点', '选择圆周上一点'],
    ),
    ConstructionTool.circleCenterNormalRadius: ToolInfo(
      ConstructionTool.circleCenterNormalRadius,
      '圆(圆心, 法向量与半径)',
      Icons.radio_button_unchecked,
      '选择圆心、法向量端点和圆周上一点',
      ToolGroup.circles,
      steps: ['选择圆心', '选择法向量端点', '选择圆周上一点'],
    ),
    ConstructionTool.circleThreePoints: ToolInfo(
      ConstructionTool.circleThreePoints,
      '圆(过三点)',
      Icons.motion_photos_on_outlined,
      '选择三个不共线的点',
      ToolGroup.circles,
      steps: ['选择第一个圆周点', '选择第二个圆周点', '选择第三个圆周点'],
    ),
    ConstructionTool.circle: ToolInfo(
      ConstructionTool.circle,
      '圆(圆心与点)',
      Icons.circle_outlined,
      '选择圆心和圆周上一点',
      ToolGroup.circles,
      steps: ['选择圆心', '选择圆周上一点'],
    ),
    ConstructionTool.arc: ToolInfo(
      ConstructionTool.arc,
      '圆弧',
      Icons.timeline,
      '选择圆心、起点和终点',
      ToolGroup.circles,
      steps: ['选择圆心', '选择圆弧起点', '选择圆弧终点'],
    ),
    ConstructionTool.circumcircleArc: ToolInfo(
      ConstructionTool.circumcircleArc,
      '外接圆弧',
      Icons.pie_chart_outline,
      '选择圆弧上的三个点',
      ToolGroup.circles,
      steps: ['选择圆弧起点', '选择圆弧经过点', '选择圆弧终点'],
    ),
    ConstructionTool.circularSector: ToolInfo(
      ConstructionTool.circularSector,
      '圆扇形',
      Icons.pie_chart,
      '选择圆心和弧的两个端点',
      ToolGroup.circles,
      steps: ['选择圆心', '选择扇形起点', '选择扇形终点'],
    ),
    ConstructionTool.circumcircleSector: ToolInfo(
      ConstructionTool.circumcircleSector,
      '外接扇形',
      Icons.donut_large,
      '选择外接弧上的三个点',
      ToolGroup.circles,
      steps: ['选择扇形弧起点', '选择弧经过点', '选择扇形弧终点'],
    ),
    ConstructionTool.ellipse: ToolInfo(
      ConstructionTool.ellipse,
      '椭圆',
      Icons.adjust,
      '选择椭圆中心、长轴端点和短轴辅助点',
      ToolGroup.curves,
      steps: ['选择椭圆中心', '选择长轴端点', '选择短轴辅助点（垂直于长轴的分量决定短轴）'],
    ),
    ConstructionTool.conic: ToolInfo(
      ConstructionTool.conic,
      '圆锥曲线',
      Icons.scatter_plot,
      '选择圆锥曲线上的五个点',
      ToolGroup.curves,
      steps: ['选择曲线上的第一个点', '继续选择点，直到五个'],
    ),
    ConstructionTool.parabola: ToolInfo(
      ConstructionTool.parabola,
      '抛物线',
      Icons.show_chart,
      '选择焦点和准线上的两点',
      ToolGroup.curves,
      steps: ['选择焦点', '选择准线第一个点', '选择准线第二个点'],
    ),
    ConstructionTool.hyperbola: ToolInfo(
      ConstructionTool.hyperbola,
      '双曲线',
      Icons.multiline_chart,
      '选择双曲线中心、实轴端点和虚轴辅助点',
      ToolGroup.curves,
      steps: ['选择双曲线中心', '选择实轴端点', '选择虚轴辅助点（垂直于实轴的分量决定虚轴）'],
    ),
    ConstructionTool.locus: ToolInfo(
      ConstructionTool.locus,
      '轨迹',
      Icons.route,
      '沿轨迹连续描点，点击首点结束',
      ToolGroup.curves,
      steps: ['选择轨迹起点', '继续描点，点击首点结束'],
    ),
    ConstructionTool.reflectionInPlane: ToolInfo(
      ConstructionTool.reflectionInPlane,
      '平面对称',
      Icons.flip,
      '选择待变换点和对称平面上的三个点',
      ToolGroup.transforms,
      steps: ['选择待变换点', '选择对称平面第一个点', '选择第二个点', '选择第三个点'],
    ),
    ConstructionTool.centralSymmetry: ToolInfo(
      ConstructionTool.centralSymmetry,
      '中心对称',
      Icons.center_focus_strong,
      '选择待变换点和对称中心',
      ToolGroup.transforms,
      steps: ['选择待变换点', '选择对称中心'],
    ),
    ConstructionTool.rotation: ToolInfo(
      ConstructionTool.rotation,
      '旋转',
      Icons.rotate_right,
      '选择待变换点、旋转轴和角度点',
      ToolGroup.transforms,
      steps: ['选择待变换点', '选择旋转轴第一点', '选择旋转轴第二点', '选择角度点'],
    ),
    ConstructionTool.translation: ToolInfo(
      ConstructionTool.translation,
      '平移',
      Icons.open_with,
      '选择待变换点和平移向量端点',
      ToolGroup.transforms,
      steps: ['选择待变换点', '选择平移向量起点', '选择平移向量终点'],
    ),
    ConstructionTool.dilation: ToolInfo(
      ConstructionTool.dilation,
      '位似',
      Icons.zoom_out_map,
      '选择待变换点、位似中心和比例点',
      ToolGroup.transforms,
      steps: ['选择待变换点', '选择位似中心', '选择比例点'],
    ),
    ConstructionTool.axialSymmetry: ToolInfo(
      ConstructionTool.axialSymmetry,
      '轴对称',
      Icons.flip_camera_android,
      '选择待变换点和对称轴两点',
      ToolGroup.transforms,
      steps: ['选择待变换点', '选择对称轴第一点', '选择对称轴第二点'],
    ),
    ConstructionTool.angle: ToolInfo(
      ConstructionTool.angle,
      '角度',
      Icons.swap_vert,
      '选择角的两边点和顶点',
      ToolGroup.measurement,
      steps: ['选择一边上的点', '选择角顶点', '选择另一边上的点'],
    ),
    ConstructionTool.distance: ToolInfo(
      ConstructionTool.distance,
      '距离/长度',
      Icons.straighten,
      '选择两个点',
      ToolGroup.measurement,
      steps: ['选择第一个点', '选择第二个点'],
    ),
    ConstructionTool.area: ToolInfo(
      ConstructionTool.area,
      '面积',
      Icons.crop_square,
      '选择平面图形的顶点，点击首点闭合',
      ToolGroup.measurement,
      steps: ['选择图形第一个顶点', '继续选择顶点，点击首点闭合'],
    ),
    ConstructionTool.volume: ToolInfo(
      ConstructionTool.volume,
      '体积',
      Icons.view_in_ar,
      '点击一个立体图形查看体积',
      ToolGroup.measurement,
      steps: ['选择要测量体积的立体图形'],
      behavior: ToolBehavior.objectAction,
    ),
    ConstructionTool.rotateView: ToolInfo(
      ConstructionTool.rotateView,
      '旋转视图',
      Icons.rotate_right,
      '拖动视图旋转',
      ToolGroup.other,
      behavior: ToolBehavior.navigation,
    ),
    ConstructionTool.panView: ToolInfo(
      ConstructionTool.panView,
      '移动视图',
      Icons.open_with,
      '拖动平移视图',
      ToolGroup.other,
      behavior: ToolBehavior.navigation,
    ),
    ConstructionTool.copyStyle: ToolInfo(
      ConstructionTool.copyStyle,
      '复制样式',
      Icons.colorize,
      '先点样式来源对象，再点目标对象',
      ToolGroup.other,
      steps: ['选择样式来源对象', '选择样式目标对象'],
      behavior: ToolBehavior.objectAction,
    ),
    ConstructionTool.text: ToolInfo(
      ConstructionTool.text,
      '文本',
      Icons.text_fields,
      '选择文本位置',
      ToolGroup.other,
      steps: ['选择文本位置'],
    ),
    ConstructionTool.equalVector: ToolInfo(
      ConstructionTool.equalVector,
      '相等向量',
      Icons.compare_arrows,
      '选择已知向量的起终点和新向量起点',
      ToolGroup.specialLines,
      steps: ['选择已知向量起点', '选择已知向量终点', '选择新向量起点'],
    ),
    ConstructionTool.polyline: ToolInfo(
      ConstructionTool.polyline,
      '折线',
      Icons.polyline,
      '连续选择折线顶点，点击首点结束',
      ToolGroup.specialLines,
      steps: ['选择折线起点', '继续选择顶点，点击首点结束'],
    ),
    ConstructionTool.polarDiameter: ToolInfo(
      ConstructionTool.polarDiameter,
      '极线/径线',
      Icons.line_axis,
      '选择点与圆锥曲线生成极线，或选择直线与有中心的圆锥曲线生成共轭径线',
      ToolGroup.specialLines,
      steps: ['选择点（极线）或直线（共轭径线）', '选择圆锥曲线'],
      behavior: ToolBehavior.objectAction,
    ),
  };
}

/// Describes the next user action in a tool workflow.
class ConstructionStep {
  final String instruction;
  final String instructionEn;
  final int clickCount;

  const ConstructionStep({
    required this.instruction,
    required this.instructionEn,
    this.clickCount = 1,
  });
}

/// The input sequence associated with a construction or object-action tool.
class ConstructionWorkflow {
  final ConstructionTool tool;
  final List<ConstructionStep> steps;

  const ConstructionWorkflow({required this.tool, required this.steps});

  static const _englishInstructions = <String, String>{
    '点击位置创建点；拖动设置高度，点击已选点切换平面/高度移动': 'Click to create a point; drag to set its height, and click a selected point to switch between plane and height movement',
    '选择底面第一个顶点': 'Select the first base vertex',
    '选择底面第二个顶点': 'Select the second base vertex',
    '选择底面第三个顶点': 'Select the third base vertex',
    '选择棱锥顶点': 'Select the pyramid apex',
    '选择一条棱的第一个端点': 'Select the first endpoint of an edge',
    '选择一条棱的第二个端点': 'Select the second endpoint of an edge',
    '选择球心': 'Select the sphere center',
    '选择球面上的一点': 'Select a point on the sphere',
    '选择第一个点': 'Select the first point',
    '选择第二个点': 'Select the second point',
    '选择第三个点': 'Select the third point',
    '选择第一个相交对象': 'Select the first intersecting object',
    '选择第二个相交对象': 'Select the second intersecting object',
    '选择第一个相交的平面或球面': 'Select the first intersecting plane or sphere',
    '选择第二个相交的平面或球面': 'Select the second intersecting plane or sphere',
    '点击对象上的位置': 'Click a location on the object',
    '选择要展开的多面体': 'Select the polyhedron to unfold',
    '选择要切换显示状态的对象': 'Select the object to show or hide',
    '选择要删除的对象': 'Select the object to delete',
    '选择要切换附着状态的点': 'Select the point to attach or detach',
    '选择曲线上的切点': 'Select a point on the curve for the tangent',
    '选择切线所依附的圆或圆锥曲线': 'Select the circle or conic for the tangent',
    '选择要测量体积的立体图形': 'Select the solid whose volume to measure',
    '选择样式来源对象': 'Select the source object for the style',
    '选择样式目标对象': 'Select the target object for the style',
    '选择要确定极线的点': 'Select a point to define the polar',
    '选择点（极线）或直线（共轭径线）':
        'Select a point for a polar, or a line for its conjugate diameter',
    '选择圆锥曲线': 'Select a conic',
    '选择线段起点': 'Select the segment start point',
    '选择线段终点': 'Select the segment end point',
    '选择起点': 'Select the start point',
    '选择方向点': 'Select a direction point',
    '选择长度': 'Select the length',
    '选择射线起点': 'Select the ray start point',
    '选择向量起点': 'Select the vector start point',
    '选择向量终点': 'Select the vector end point',
    '选择多边形顶点': 'Select a polygon vertex',
    '继续选择顶点，点击首点闭合': 'Select more vertices, then click the first to close',
    '选择边的第一个端点': 'Select the first endpoint of an edge',
    '选择边的第二个端点': 'Select the second endpoint of an edge',
    '选择垂线经过点': 'Select a point on the perpendicular line',
    '选择目标直线上的点': 'Select a point on the reference line',
    '选择目标直线方向点': 'Select another point on the reference line',
    '选择经过点': 'Select a point the line passes through',
    '选择方向线上的第一个点': 'Select the first point on the direction line',
    '选择方向线上的第二个点': 'Select the second point on the direction line',
    '选择一边上的点': 'Select a point on one side of the angle',
    '选择角顶点': 'Select the angle vertex',
    '选择另一边上的点': 'Select a point on the other side of the angle',
    '选择高度点': 'Select a point to set the height',
    '选择半径长度': 'Select the radius length',
    '选择底面圆心': 'Select the base center',
    '选择底面半径点': 'Select a point on the base radius',
    '选择圆锥顶点': 'Select the cone apex',
    '选择顶面圆心': 'Select the top center',
    '选择旋转轴第一点': 'Select the first point on the axis of rotation',
    '选择旋转轴第二点': 'Select the second point on the axis of rotation',
    '选择母线第一点': 'Select the first point on the generatrix',
    '选择母线第二点': 'Select the second point on the generatrix',
    '选择平面上一点': 'Select a point on the plane',
    '选择法向量端点': 'Select the normal vector endpoint',
    '选择参考平面第一个点': 'Select the first point on the reference plane',
    '选择参考平面第二个点': 'Select the second point on the reference plane',
    '选择参考平面第三个点': 'Select the third point on the reference plane',
    '选择新平面经过点': 'Select a point on the new plane',
    '选择轴线第一点': 'Select the first point on the axis',
    '选择轴线第二点': 'Select the second point on the axis',
    '选择圆周上一点': 'Select a point on the circumference',
    '选择圆心': 'Select the circle center',
    '选择第一个圆周点': 'Select the first point on the circumference',
    '选择第二个圆周点': 'Select the second point on the circumference',
    '选择第三个圆周点': 'Select the third point on the circumference',
    '选择圆弧起点': 'Select the arc start point',
    '选择圆弧终点': 'Select the arc end point',
    '选择圆弧经过点': 'Select a point on the arc',
    '选择扇形起点': 'Select the sector start point',
    '选择扇形终点': 'Select the sector end point',
    '选择扇形弧起点': 'Select the sector arc start point',
    '选择弧经过点': 'Select a point on the arc',
    '选择扇形弧终点': 'Select the sector arc end point',
    '选择椭圆中心': 'Select the ellipse center',
    '选择长轴端点': 'Select the major-axis endpoint',
    '选择短轴端点': 'Select the minor-axis endpoint',
    '选择短轴辅助点（垂直于长轴的分量决定短轴）': 'Select an auxiliary point; its component perpendicular to the major axis sets the minor axis',
    '选择曲线上的第一个点': 'Select the first point on the curve',
    '继续选择点，直到五个': 'Continue selecting points until you have five',
    '选择焦点': 'Select the focus',
    '选择准线第一个点': 'Select the first point on the directrix',
    '选择准线第二个点': 'Select the second point on the directrix',
    '选择双曲线中心': 'Select the hyperbola center',
    '选择实轴端点': 'Select the real-axis endpoint',
    '选择虚轴端点': 'Select the conjugate-axis endpoint',
    '选择虚轴辅助点（垂直于实轴的分量决定虚轴）': 'Select an auxiliary point; its component perpendicular to the real axis sets the conjugate axis',
    '选择轨迹起点': 'Select the starting point of the locus',
    '继续描点，点击首点结束': 'Continue adding points, then click the first to finish',
    '选择待变换点': 'Select the point to transform',
    '选择对称平面第一个点': 'Select the first point on the reflection plane',
    '选择对称中心': 'Select the center of symmetry',
    '选择角度点': 'Select a point to set the angle',
    '选择平移向量起点': 'Select the translation vector start point',
    '选择平移向量终点': 'Select the translation vector end point',
    '选择位似中心': 'Select the center of dilation',
    '选择比例点': 'Select a point to set the scale factor',
    '选择垂直平面方向点': 'Select a direction point on the perpendicular plane',
    '选择对称轴第一点': 'Select the first point on the axis of symmetry',
    '选择对称轴第二点': 'Select the second point on the axis of symmetry',
    '选择图形第一个顶点': 'Select the first vertex of the shape',
    '选择文本位置': 'Select the text position',
    '选择已知向量起点': 'Select the known vector start point',
    '选择已知向量终点': 'Select the known vector end point',
    '选择新向量起点': 'Select the new vector start point',
    '选择折线起点': 'Select the polyline start point',
    '继续选择顶点，点击首点结束':
        'Continue selecting vertices, then click the first to finish',
  };

  static final Map<ConstructionTool, ConstructionWorkflow> workflows = {
    for (final info in ToolInfo.all.values)
      if (info.steps.isNotEmpty)
        info.tool: ConstructionWorkflow(
          tool: info.tool,
          steps: [
            for (final instruction in info.steps)
              ConstructionStep(
                instruction: instruction,
                instructionEn:
                    _englishInstructions[instruction] ??
                    'Continue construction',
                clickCount: instruction == '继续选择点，直到五个'
                    ? 4
                    : instruction.contains('继续')
                    ? 0
                    : 1,
              ),
          ],
        ),
  };
}
