@TestOn('browser')
library;

import 'dart:convert';
import 'dart:typed_data';

import 'package:flutter_test/flutter_test.dart';
import 'package:stroom/utils/web_thumbnail.dart';

// A tiny 32x32 2-second H.264 MP4 (5 fps, CRF 40) generated with FFmpeg,
// base64-encoded. Used to verify the web blob-URL -> canvas pipeline.
const _tinyMp4Base64 =
    'AAAAIGZ0eXBpc29tAAACAGlzb21pc28yYXZjMW1wNDEAAAAIZnJlZQAABJttZGF0AAACUwYF//9P3EXpvebZSLeWLNgg2SPu73gy'
    'NjQgLSBjb3JlIDE2NSByMzIyMyAwNDgwY2IwIC0gSC4yNjQvTVBFRy00IEFWQyBjb2RlYyAtIENvcHlsZWZ0IDIwMDMtMjAyNSAt'
    'IGh0dHA6Ly93d3cudmlkZW9sYW4ub3JnL3gyNjQuaHRtbCAtIG9wdGlvbnM6IGNhYmFjPTAgcmVmPTEgZGVibG9jaz0wOjA6MCBh'
    'bmFseXNlPTA6MCBtZT1kaWEgc3VibWU9MCBwc3k9MSBwc3lfcmQ9MS4wMDowLjAwIG1peGVkX3JlZj0wIG1lX3JhbmdlPTE2IGNo'
    'cm9tYV9tZT0xIHRyZWxsaXM9MCA4eDhkY3Q9MCBjcW09MCBkZWFkem9uZT0yMSwxMSBmYXN0X3Bza2lwPTEgY2hyb21hX3FwX29m'
    'ZnNldD0wIHRocmVhZHM9MSBsb29rYWhlYWRfdGhyZWFkcz0xIHNsaWNlZF90aHJlYWRzPTAgbnI9MCBkZWNpbWF0ZT0xIGludGVy'
    'bGFjZWQ9MCBibHVyYXlfY29tcGF0PTAgY29uc3RyYWluZWRfaW50cmE9MCBiZnJhbWVzPTAgd2VpZ2h0cD0wIGtleWludD0yNTAg'
    'a2V5aW50X21pbj01IHNjZW5lY3V0PTAgaW50cmFfcmVmcmVzaD0wIHJjPWNyZiBtYnRyZWU9MCBjcmY9NDAuMCBxY29tcD0wLjYw'
    'IHFwbWluPTAgcXBtYXg9NjkgcXBzdGVwPTQgaXBfcmF0aW89MS40MCBhcT0wAIAAAAEOZYiEOgxgAfDR71Dkw1RZ/UYAI2/5Xhf5'
    'MDxEl+yHiMBj548gQz3PwxAMEhgcdgrZGRbmGuDyw8sABqyTB0z/n7yvePqmBECYLQJgMYAaD5dyIMa4oBl/4OjLLr4S/n0wAzex'
    'Vn/N8F0+tGQZ+74YQoAmEFRUHcQuzDNDFeWDliaZxpCDD/QM8vXFoEwWgTAWcAVkFBIT5SSZf6+4AaDslJvL3+RCS5SAwhXISkai'
    'xvhZewGSlgcAAlAUIAAvQSOCwiUCHoGofOA1IR3KAEXdQ3P8CzgAXPKA3dgRFiae38AYb0TOq8LohZdOVXLfyCn2A6Y5YQgDQMLV'
    'tbmAq7laEmwybhyjnsDnXlGBB1PoAAAACUGaIEJ9X+phsAAAABZBmkEnw3FOS4qBSv2z/w3FHapnko38AAAAIkGaYafDEYQN8B7a'
    'eK2V56Ce5dPTwxc3H2jTbwERcvxPSUgAAAAdQZqAqfBRJysQuIfmQAvhifmYZRRP1FjMOSgzn8AAAAAmQZqg6fDFM/TfSK58AOUc'
    'QpAr/iB0ZMeGIqyfxeSxigG/yfLJpogAAAAZQZrA6fBJTFHH/GRR8OWxTjDIqMOoq80TeAAAACJBmuBKfDEQP8vG6cyE45qi3jaB'
    'b3hiWfNxymGVDY46aW7+AAAAIkGbAEp8ORDwd+zoMyKOXmhl1Pw5E+D7jHmYVGHN3w1GpswAAAAlQZsgSnwxP/FGdkf9mQxHPYdo'
    '2eht8MSejimRkMZbKjD/JQZzgAAAA0ttb292AAAAbG12aGQAAAAAAAAAAAAAAAAAAAPoAAAH0AABAAABAAAAAAAAAAAAAAAAAQAA'
    'AAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACAAACdXRyYWsAAABcdGto'
    'ZAAAAAMAAAAAAAAAAAAAAAEAAAAAAAAH0AAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAEAA'
    'AAAAIAAAACAAAAAAACRlZHRzAAAAHGVsc3QAAAAAAAAAAQAAB9AAAAAAAAEAAAAAAe1tZGlhAAAAIG1kaGQAAAAAAAAAAAAAAAAA'
    'ACgAAABQAFXEAAAAAAAtaGRscgAAAAAAAAAAdmlkZQAAAAAAAAAAAAAAAFZpZGVvSGFuZGxlcgAAAAGYbWluZgAAABR2bWhkAAAA'
    'AQAAAAAAAAAAAAAAJGRpbmYAAAAcZHJlZgAAAAAAAAABAAAADHVybCAAAAABAAABWHN0YmwAAAC4c3RzZAAAAAAAAAABAAAAqGF2'
    'YzEAAAAAAAAAAQAAAAAAAAAAAAAAAAAAAAAAIAAgAEgAAABIAAAAAAAAAAEVTGF2YzYyLjI4LjEwMiBsaWJ4MjY0AAAAAAAAAAAA'
    'AAAY//8AAAAuYXZjQwFCwAr/4QAWZ0LACtolsBEAAAMAAQAAAwAKDxImoAEABWjOA5yAAAAAEHBhc3AAAAABAAAAAQAAABRidHJ0'
    'AAAAAAAAEkwAAAAAAAAAGHN0dHMAAAAAAAAAAQAAAAoAAAgAAAAAFHN0c3MAAAAAAAAAAQAAAAEAAAAcc3RzYwAAAAAAAAABAAAA'
    'AQAAAAoAAAABAAAAPHN0c3oAAAAAAAAAAAAAAAoAAANpAAAADQAAABoAAAAmAAAAIQAAACoAAAAdAAAAJgAAACYAAAApAAAAFHN0'
    'Y28AAAAAAAAAAQAAADAAAABidWR0YQAAAFptZXRhAAAAAAAAACFoZGxyAAAAAAAAAABtZGlyYXBwbAAAAAAAAAAAAAAAAC1pbHN0'
    'AAAAJal0b28AAAAdZGF0YQAAAAEAAAAATGF2ZjYyLjEyLjEwMg==';

void main() {
  test('web generateThumbnailFromBytes returns JPEG bytes for a real video',
      () async {
    final videoBytes = base64Decode(_tinyMp4Base64);
    expect(videoBytes.length, greaterThan(0));

    final thumb = await generateThumbnailFromBytes(videoBytes);

    // JPEG magic bytes 0xFF 0xD8
    expect(thumb, isNotNull);
    expect(thumb!.length, greaterThan(2));
    expect(thumb[0], 0xFF);
    expect(thumb[1], 0xD8);
  });

  test('web generateThumbnailFromBytes returns null for garbage bytes',
      () async {
    final garbage =
        Uint8List.fromList(List<int>.generate(2048, (i) => i % 256));
    final thumb = await generateThumbnailFromBytes(garbage);
    expect(thumb, isNull);
  });
}
